// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TasksManagement.Data;

namespace TasksManagement.Data.Migrations
{
    [DbContext(typeof(TaskManagementDBContext))]
    partial class TaskManagementDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("TasksManagement.Core.Entities.Role", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired();

                    b.HasKey("ID");

                    b.ToTable("Roles");

                    b.HasData(
                        new { ID = 1, Name = "Admin" },
                        new { ID = 2, Name = "Support" }
                    );
                });

            modelBuilder.Entity("TasksManagement.Core.Entities.Task", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("AssignedToUserID");

                    b.Property<DateTime>("Created");

                    b.Property<string>("Description");

                    b.Property<int>("OwnerUserID");

                    b.Property<string>("Title")
                        .IsRequired();

                    b.HasKey("ID");

                    b.HasIndex("AssignedToUserID");

                    b.HasIndex("OwnerUserID");

                    b.ToTable("Tasks");

                    b.HasData(
                        new { ID = 1, Created = new DateTime(2018, 11, 30, 2, 21, 13, 217, DateTimeKind.Local), Description = "Task 1 Description", OwnerUserID = 2, Title = "Task1" },
                        new { ID = 2, Created = new DateTime(2018, 11, 30, 2, 21, 13, 218, DateTimeKind.Local), Description = "Task 2 Description", OwnerUserID = 3, Title = "Task2" }
                    );
                });

            modelBuilder.Entity("TasksManagement.Core.Entities.User", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<int>("RoleID");

                    b.HasKey("ID");

                    b.HasIndex("RoleID");

                    b.ToTable("Users");

                    b.HasData(
                        new { ID = 1, Name = "Admin1", RoleID = 1 },
                        new { ID = 2, Name = "Support1", RoleID = 2 },
                        new { ID = 3, Name = "Support2", RoleID = 2 }
                    );
                });

            modelBuilder.Entity("TasksManagement.Core.Entities.Task", b =>
                {
                    b.HasOne("TasksManagement.Core.Entities.User", "AssignedToUser")
                        .WithMany("AssignedTasks")
                        .HasForeignKey("AssignedToUserID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("TasksManagement.Core.Entities.User", "OwnerUser")
                        .WithMany("OwnedTasks")
                        .HasForeignKey("OwnerUserID")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("TasksManagement.Core.Entities.User", b =>
                {
                    b.HasOne("TasksManagement.Core.Entities.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleID")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
